[package]
name = "secured-enclave"
version = "0.1.0"
authors = ["mikesposito"]
edition = "2021"
license = "MIT"
description = "Part of secured: a lightweight, easy-to-use Rust package for file encryption and decryption, suitable for both CLI and library integration in Rust applications."

[dependencies.chacha20poly1305]
version = "~0.9.0"

[dependencies.hmac]
version = "~0.12.1"

[dependencies.pbkdf2]
version = "~0.12.2"

[dependencies.rand_core]
version = "~0.6.4"
features = ["getrandom"]

[dependencies.sha2]
version = "~0.10.5"
